version: "3"
services:
  web:
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/code
      - /home/node/code/node_modules
    links:
      - server
  server:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    ports:
      - "8000:8000"
      - "56745:56745"
    volumes:
      - .:/home/node/code
      - /home/node/code/node_modules