export const SET_BRUSH_SIZE = 'SET_BRUSH_SIZE';
export const SET_BRUSH_ALPHA = 'SET_BRUSH_ALPHA';
export const SET_COLOR = 'SET_COLOR';
export const BEGIN_RESET_CANVAS = 'BEGIN_RESET_CANVAS';
export const FINISH_RESET_CANVAS = 'FINISH_RESET_CANVAS';